# Copyright 2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.5

EAPI=8

CRATES="
	aho-corasick@0.7.20
	anyhow@1.0.70
	autocfg@1.1.0
	bitflags@1.3.2
	bitflags@2.5.0
	byteorder@1.4.3
	cc@1.0.79
	cfg-if@1.0.0
	cfg_aliases@0.2.1
	clap@4.1.11
	clap_derive@4.1.9
	clap_lex@0.3.3
	comfy-table@7.1.1
	console@0.15.8
	crossterm@0.27.0
	crossterm_winapi@0.9.1
	encode_unicode@0.3.6
	errno-dragonfly@0.1.2
	errno@0.2.8
	heck@0.4.1
	hermit-abi@0.3.1
	io-lifetimes@1.0.9
	is-terminal@0.4.5
	itoa@1.0.6
	lazy_static@1.4.0
	libc@0.2.155
	linux-personality@2.0.0
	linux-raw-sys@0.1.4
	lock_api@0.4.9
	log@0.4.17
	memchr@2.5.0
	nix@0.29.0
	once_cell@1.17.1
	os_str_bytes@6.5.0
	parking_lot@0.12.1
	parking_lot_core@0.9.7
	proc-macro-error-attr@1.0.4
	proc-macro-error@1.0.4
	proc-macro2@1.0.53
	quote@1.0.26
	redox_syscall@0.2.16
	regex-syntax@0.6.29
	regex@1.7.2
	rustix@0.36.11
	rustversion@1.0.12
	ryu@1.0.13
	scopeguard@1.1.0
	serde@1.0.158
	serde_derive@1.0.158
	serde_json@1.0.94
	serde_repr@0.1.12
	smallvec@1.10.0
	strsim@0.10.0
	strum@0.26.2
	strum_macros@0.26.2
	syn@1.0.109
	syn@2.0.8
	syscalls@0.6.18
	termcolor@1.2.0
	unicode-ident@1.0.8
	unicode-width@0.1.10
	users@0.11.0
	version_check@0.9.4
	winapi-i686-pc-windows-gnu@0.4.0
	winapi-util@0.1.5
	winapi-x86_64-pc-windows-gnu@0.4.0
	winapi@0.3.9
	windows-sys@0.45.0
	windows-sys@0.52.0
	windows-targets@0.42.2
	windows-targets@0.52.5
	windows_aarch64_gnullvm@0.42.2
	windows_aarch64_gnullvm@0.52.5
	windows_aarch64_msvc@0.42.2
	windows_aarch64_msvc@0.52.5
	windows_i686_gnu@0.42.2
	windows_i686_gnu@0.52.5
	windows_i686_gnullvm@0.52.5
	windows_i686_msvc@0.42.2
	windows_i686_msvc@0.52.5
	windows_x86_64_gnu@0.42.2
	windows_x86_64_gnu@0.52.5
	windows_x86_64_gnullvm@0.42.2
	windows_x86_64_gnullvm@0.52.5
	windows_x86_64_msvc@0.42.2
	windows_x86_64_msvc@0.52.5
"

inherit cargo

DESCRIPTION="lurk is a pretty (simple) alternative to strace."
HOMEPAGE="https://github.com/JakWai01/lurk"
SRC_URI="https://github.com/JakWai01/${PN}/archive/refs/tags/v${PV}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+="
	BSD-2 MIT Unicode-3.0
	|| ( Apache-2.0 Boost-1.0 )
"
SLOT="0"
KEYWORDS="~amd64"

src_configure() {
	cargo_src_configure
}

src_install() {
	cargo_src_install
}
